import ShopNav from "../components/Nav/ShopNav";

export const metadata = {
    title: 'Shop page',
    description: 'Generated by create next app',
}

const ShopLayout = ({ children }) => {
    return (
        <div>
            {/* You can put component that you want to just show in shop endpoint */}

            {children}
        </div>
    )
}
export default ShopLayout;