'use client';
import { Provider } from 'react-redux';
import './globals.css';
import { Inter } from 'next/font/google';
import { persistor, store } from './redux/store';
import { PersistGate } from 'redux-persist/integration/react';
import Nav from './components/Nav';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Online shopping site',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}>
            <Nav />
            {children}
          </PersistGate>
        </Provider>
      </body>
    </html>
  );
}
